### ISSUE TITLE
[bug?]bots can't drink or eat

### ISSUE THREAD

**Issue by yyhhrr** [blueboy/portalclassic#14]
I test the newest portalclassic code develop branch with 14lv mage and priest bots.The bots awayls stand up and down while they drink.Bots can only restore 50% mana then they stop.The issue seems like https://github.com/blueboy/portal/issues/42.  I even test the bots with use the manual command "/t botname use item some drink or eat",it just the same.So i thought maybe there is some other problem.Sorry for poor english.I am chinese.

**Comment by cala** [comment]
Fixed in the develop branch by @Krullgor in https://github.com/blueboy/portalclassic/commit/995aab3756ac7f4984d7b73265c4b57dab5ffcff
I let the issue open for now until the two branches are merged

**Comment by cala** [comment]
Fixed long ago in develop branch, now fixed also in master.
