### ISSUE TITLE
new loot system

### ISSUE THREAD

**Issue by yyhhrr** [blueboy/portalclassic#18]
with new loot system,when the mob skinable ,bot will stand around the mob till you skinned mob.

**Comment by cala** [comment]
This was supposed to be fixed by https://github.com/blueboy/portalclassic/commit/9b732a02521a951170562e7a029f63258b8bf1bf
Can you confirm that you still have the bug with this commit, please ?

**Comment by yyhhrr** [comment]
Sorry.I Don't noteiced the commit.I will test later.Thank you.
