### ISSUE TITLE
Bot can't loot anything

### ISSUE THREAD

**Issue by yyhhrr** [blueboy/portalclassic#19]
They do the loot action,but loot nothing with recently update.

**Comment by cala** [comment]
Is this on master branch, develop branch or both ? Does it occurs 100% of the time or only sometime?

**Comment by yyhhrr** [comment]
Only occurs on the master branch,100%.
Develop branch works  well.

**Comment by cala** [comment]
Strange, that was an issue that I tested and was supposedly fixed by cyberium in https://github.com/blueboy/portalclassic/commit/cdc07032a8a7d750653b722b1f2944baba34d0cb. I assume you tested it on a 100% clean build/branch?

**Comment by yyhhrr** [comment]
Yes,I tested it on a 100% clean build/branch(I downloaded directly from the https://github.com/blueboy/portalclassic/master.zip).My boost version 1.6.Is this related with this issue?

**Comment by cala** [comment]
This is not related to your boost version. Something is wrong in the way Playerbot code handles the OPcode for the loots after the switch to boost. I saw what is the problem but I don't understand why neither why I did not see it when I tested the code after switching to boost...

**Comment by ryancheung** [comment]
I found Bot does casting spells, but all the spellid is 0, after i debugged.
