### ISSUE TITLE
Random crash in MC.

### ISSUE THREAD

**Issue by yyhhrr** [blueboy/portalclassic#20]
When  my bots in the MC and fight with Firelord,there was random server crash sometimes,I thought maybe the Firelord's spell Summon Lava Spawn lead the crash.Can anyone reproduce this?

**Comment by cala** [comment]
Hi, could you confirm that:
- this **does not** occurs on clean CMaNGOS Classic core
- this **does** occurs on clean portalclassic install
Thanks.

**Comment by cala** [comment]
Any news regarding this issue?

**Comment by yyhhrr** [comment]
This is my bad.Because this does't occurs on clean portalclassic install.
I use this patch lead the issues.https://github.com/yyhhrr/portalclassic/commit/ae5689c2d567769afa595bcb93cb1ab85910c7c8
and partially fixed by this commit.https://github.com/yyhhrr/portalclassic/commit/79e646adb432cb3ccc311c29bf90121b87997cf3
And if you want use 40 bot to raid,maybe this will help.

**Comment by cala** [comment]
Thanks for the hint about the 40 bots raid. I'm closing this issue as it is not related to current repository.
