### ISSUE TITLE
Bot Looting Quest Items

### ISSUE THREAD

**Issue by acgritt** [blueboy/portalclassic#22]
For some reason, if I have multiple bots loaded, when I loot a mob that has a quest item (say a kolkar head) only one of the bot will loot that item.  I either have to log off and log on to the other bot and loot the corpse quickly or wait and kill the mob again and again (once for each of the other bots that is running).

**Comment by cala** [comment]
Thanks for the report. Is the behaviour the same if the item is supposed to drop for everyone (like a dungeon boss' head) or only for one player at a time (like normal mob's head, for example)?

**Comment by acgritt** [comment]
I have only taken them into Ragefire Chasm for instances so far and the boss in there where you have to get his head only one bot and myself was able to loot the head.  I could not get the other two bots to loot the head.

**Comment by cala** [comment]
Issue confirmed. I will investigate this.

**Comment by cala** [comment]
Should be fixed now.
