### ISSUE TITLE
need some help here 

### ISSUE THREAD

**Issue by rikkuzhou** [blueboy/portalclassic#25]
would someone help me with the installation?

**Comment by rikkuzhou** [comment]
Maybe I am not quit followed by the instructions.
I have cloned the MaNGOS core and then what should I ? Clone the Playerbot(blueboy/portal) for CMaNGOS-Classic or 

cd <local repository> 
git pull git://github.com/playerbot/mangos.git <branch name>

so is this git pull will merge the Playerbot(blueboy/portal) for CMaNGOS-Classic or I need to download first 

and step 3 
3. If you wish to update an existing local repository, then repeat instruction 2. All changes since
the last merge will then be merged into the local repository

here i have merged the playerbot into mangos already right ?so it means I update the mangos file right ?  I don't understand the step 3

**Comment by rikkuzhou** [comment]
finally I get it done

First merge the playerbot code into your Mangos code   I get it done

Follow the install instructions of Mangos in building mangos, building ScriptDev2, extracting map data, installing SQL data (DB, SD2, ACID), etc.     I get it done

In the folder "/sql/playerbotai" you'll find the SQL data for playerbot (install on the "characters" database) 

is this necessarily ? because I haven't done it yet  but I find I can use .bot add xx already

**Comment by cala** [comment]
These SQL files are used if you want playerbot to save some of the NPCs set up/orders (like delay time or resistances).

**Comment by cala** [comment]
As you merged successfully, I'm closing the issue. :)
