### ISSUE TITLE
Combat orders not working 

### ISSUE THREAD

**Issue by Brodywood900** [blueboy/portalclassic#26]
I recently complied the server (Win32 release) and got it running when I was trying out the commands I realized that the playerbots will not pick up the combat orders this is an example of what I type in .bot co Botguy tank in previous builds the playerbot would respond back to you saying I tank or something similar but I don't get a response back I also try to tell them to pull they say I cannot pull as I do not have combat orders to tank I don't know if I am typing the command in right or something went wrong when it was compiling I did have ALOT of warnings (about 1000) though there doesn't seem to be any requirements to make them listen to combat orders I also tried with a healer and nothing so I don't think the combat orders are working properly at least for me please help me out I would like to have combat orders to do dungeons with proper roles for the bots

**Comment by cala** [comment]
Greetings,

The documentation was out of date after last year backports. I updated it today. You should find the correct syntax for the combat orders after https://github.com/blueboy/portalclassic/commit/394fdd1293d9d953bc43a8af6036e4bf7fd77441 in /doc/playerbot/commands.txt

I hope this helps.

**Comment by Brodywood900** [comment]
Hay thanks cala love your work btw :)
