### ISSUE TITLE
compile blues

### ISSUE THREAD

**Issue by madmax765** [blueboy/portalclassic#31]
Some resion i can not seem to compile now Commits on May 15, 2017  e107c6d8d41c2d8ccd831fddc9279a5fdcdfa201
running windows 10 pro, VS2107

`------ Build started: Project: zlib, Configuration: Release x64 ------
  adler32.c
  compress.c
  crc32.c
  deflate.c
  gzclose.c
  gzlib.c
  gzread.c
..\..\dep\zlib\gzread.c(319): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
..\..\dep\zlib\gzread.c(400): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
..\..\dep\zlib\gzread.c(472): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  gzwrite.c
..\..\dep\zlib\gzwrite.c(212): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
..\..\dep\zlib\gzwrite.c(232): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
..\..\dep\zlib\gzwrite.c(371): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  infback.c
  inffast.c
  inflate.c
  inftrees.c
  trees.c
  uncompr.c
  zutil.c
  Generating Code...
  zlib.vcxproj -> C:\portalclassic\win\VC140\.\zlib__x64_Release\zlib.lib
------ Build started: Project: framework, Configuration: Release x64 ------
  ObjectLifeTime.cpp
  EventProcessor.cpp
  Generating Code...
  framework.vcxproj -> C:\portalclassic\win\VC140\.\framework__x64_Release\framework.lib
------ Build started: Project: genrevision, Configuration: Release x64 ------
  genrevision.cpp
  Generating code
  Finished generating code
  All 246 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  genrevision.vcxproj -> C:\portalclassic\win\VC140\.\genrevision__x64_Release\genrevision.exe
  genrevision.vcxproj -> .\genrevision__x64_Release\genrevision.pdb (Full PDB)
------ Build started: Project: shared, Configuration: Release x64 ------
  Extract revision
  AuthCrypt.cpp
  BigNumber.cpp
  Hmac.cpp
  Sha1.cpp
  ByteBuffer.cpp
  Common.cpp
  Config.cpp
  Database.cpp
  DatabaseMysql.cpp
  DBCFileLoader.cpp
  Field.cpp
  QueryResultMysql.cpp
  SqlDelayThread.cpp
  SqlOperations.cpp
  SqlPreparedStatement.cpp
  SQLStorage.cpp
  Log.cpp
  Listener.cpp
  Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
  - add -D_WIN32_WINNT=0x0501 to the compiler command line; or
  - add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
  Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
  PacketBuffer.cpp
  Socket.cpp
  Generating Code...
  Compiling...
  ProgressBar.cpp
  ServiceWin32.cpp
  Threading.cpp
  Util.cpp
  Generating Code...
  md5.c
  shared.vcxproj -> C:\portalclassic\win\VC140\.\shared__x64_Release\shared.lib
------ Build started: Project: g3dlite, Configuration: Release x64 ------
  AABox.cpp
  Box.cpp
  Crypto.cpp
  format.cpp
  Matrix3.cpp
  Plane.cpp
  RegistryUtil.cpp
  System.cpp
  Triangle.cpp
  Vector3.cpp
  Vector4.cpp
  debugAssert.cpp
  fileutils.cpp
  g3dmath.cpp
  g3dfnmatch.cpp
  prompt.cpp
  stringutils.cpp
  Any.cpp
  BinaryFormat.cpp
  BinaryInput.cpp
  Generating Code...
  Compiling...
  BinaryOutput.cpp
  Capsule.cpp
  CollisionDetection.cpp
  CoordinateFrame.cpp
  Cylinder.cpp
  Line.cpp
  LineSegment.cpp
  Log.cpp
C:\Program Files (x86)\Windows Kits\8.1\Include\um\imagehlp.h(1873): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
C:\Program Files (x86)\Windows Kits\8.1\Include\um\imagehlp.h(3519): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
  Matrix4.cpp
  MemoryManager.cpp
  Quat.cpp
  Random.cpp
  Ray.cpp
  ReferenceCount.cpp
  Sphere.cpp
  TextInput.cpp
  TextOutput.cpp
  UprightFrame.cpp
  Vector2.cpp
  PhysicsFrame.cpp
  Generating Code...
  Compiling...
  FileSystem.cpp
  uint128.cpp
  Generating Code...
  g3dlite.vcxproj -> C:\portalclassic\win\VC140\.\g3dlite__x64_Release\g3dlite.lib
------ Build started: Project: Detour, Configuration: Release x64 ------
  DetourAlloc.cpp
  DetourCommon.cpp
  DetourNavMesh.cpp
  DetourNavMeshBuilder.cpp
  DetourNavMeshQuery.cpp
  DetourNode.cpp
  Generating Code...
  Detour.vcxproj -> C:\portalclassic\dep\recastnavigation\Detour\win\VC140\\..\..\..\..\lib\x64_Release\Detour.lib
------ Build started: Project: game, Configuration: Release x64 ------
  pchdef.cpp
c:\portalclassic\src\game\playerbot/PlayerbotAI.h(502): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
  AccountMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\AccountMgr.cpp': No such file or directory
  AddonHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\AddonHandler.cpp': No such file or directory
  AggressorAI.cpp
  CreatureAI.cpp
  GuardAI.cpp
  GuardianAI.cpp
  NullCreatureAI.cpp
  PetAI.cpp
  ReactorAI.cpp
  TotemAI.cpp
  CreatureAIRegistry.cpp
  CreatureAISelector.cpp
  CreatureEventAI.cpp
  CreatureEventAIMgr.cpp
  escort_ai.cpp
  follower_ai.cpp
  guard_ai.cpp
  pet_ai.cpp
  precompiled.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\AI\ScriptDevAI\include\precompiled.cpp': No such file or directory
  sc_creature.cpp
  Generating Code...
  Compiling...
  sc_grid_searchers.cpp
  sc_instance.cpp
  ScriptDevAIMgr.cpp
  battlegrounds.cpp
  alterac_mountains.cpp
  arathi_highlands.cpp
  blackrock_depths.cpp
  boss_ambassador_flamelash.cpp
  boss_emperor_dagran_thaurissan.cpp
  boss_general_angerforge.cpp
  boss_high_interrogator_gerstahn.cpp
  instance_blackrock_depths.cpp
  boss_gyth.cpp
  boss_overlord_wyrmthalak.cpp
  boss_pyroguard_emberseer.cpp
  instance_blackrock_spire.cpp
  boss_broodlord_lashlayer.cpp
  boss_chromaggus.cpp
  boss_ebonroc.cpp
  boss_firemaw.cpp
  Generating Code...
  Compiling...
  boss_flamegor.cpp
  boss_nefarian.cpp
  boss_razorgore.cpp
  boss_vaelastrasz.cpp
  boss_victor_nefarius.cpp
  instance_blackwing_lair.cpp
  blasted_lands.cpp
  boss_kazzak.cpp
  burning_steppes.cpp
  boss_mr_smite.cpp
  deadmines.cpp
  instance_deadmines.cpp
  dun_morogh.cpp
  eastern_plaguelands.cpp
  elwynn_forest.cpp
  boss_thermaplugg.cpp
  gnomeregan.cpp
  instance_gnomeregan.cpp
  hinterlands.cpp
  ironforge.cpp
  Generating Code...
  Compiling...
  loch_modan.cpp
  boss_baron_geddon.cpp
  boss_garr.cpp
  boss_gehennas.cpp
  boss_golemagg.cpp
  boss_lucifron.cpp
  boss_magmadar.cpp
  boss_majordomo_executus.cpp
  boss_ragnaros.cpp
  boss_shazzrah.cpp
  boss_sulfuron_harbinger.cpp
  instance_molten_core.cpp
  molten_core.cpp
  boss_anubrekhan.cpp
  boss_faerlina.cpp
  boss_four_horsemen.cpp
  boss_gluth.cpp
  boss_gothik.cpp
  boss_grobbulus.cpp
  boss_heigan.cpp
  Generating Code...
  Compiling...
  boss_kelthuzad.cpp
  boss_loatheb.cpp
  boss_maexxna.cpp
  boss_noth.cpp
  boss_patchwerk.cpp
  boss_razuvious.cpp
  boss_sapphiron.cpp
  boss_thaddius.cpp
  instance_naxxramas.cpp
  redridge_mountains.cpp
  boss_arcanist_doan.cpp
  boss_herod.cpp
  boss_mograine_and_whitemane.cpp
  instance_scarlet_monastery.cpp
  boss_darkmaster_gandling.cpp
  boss_jandice_barov.cpp
  instance_scholomance.cpp
  scholomance.cpp
  searing_gorge.cpp
  instance_shadowfang_keep.cpp
  Generating Code...
  Compiling...
  shadowfang_keep.cpp
  silverpine_forest.cpp
  stormwind_city.cpp
  stranglethorn_vale.cpp
  boss_baroness_anastari.cpp
  boss_cannon_master_willey.cpp
  boss_dathrohan_balnazzar.cpp
  boss_maleki_the_pallid.cpp
  instance_stratholme.cpp
  stratholme.cpp
  instance_sunken_temple.cpp
  sunken_temple.cpp
  swamp_of_sorrows.cpp
  tirisfal_glades.cpp
  boss_archaedas.cpp
  instance_uldaman.cpp
  uldaman.cpp
  undercity.cpp
  western_plaguelands.cpp
  westfall.cpp
  Generating Code...
  Compiling...
  wetlands.cpp
  boss_arlokk.cpp
  boss_hakkar.cpp
  boss_hazzarah.cpp
  boss_jeklik.cpp
  boss_jindo.cpp
  boss_mandokir.cpp
  boss_marli.cpp
  boss_renataki.cpp
  boss_thekal.cpp
  boss_venoxis.cpp
  instance_zulgurub.cpp
  example_creature.cpp
  example_escort.cpp
  example_gossip_codebox.cpp
  example_misc.cpp
  ashenvale.cpp
  azshara.cpp
  instance_blackfathom_deeps.cpp
  boss_azuregos.cpp
  Generating Code...
  Compiling...
  darkshore.cpp
  desolace.cpp
  dire_maul.cpp
  instance_dire_maul.cpp
  durotar.cpp
  dustwallow_marsh.cpp
  felwood.cpp
  feralas.cpp
  boss_noxxion.cpp
  moonglade.cpp
  mulgore.cpp
  boss_onyxia.cpp
  instance_onyxias_lair.cpp
  orgrimmar.cpp
  instance_razorfen_downs.cpp
  razorfen_downs.cpp
  instance_razorfen_kraul.cpp
  razorfen_kraul.cpp
  boss_ayamiss.cpp
  boss_buru.cpp
  Generating Code...
  Compiling...
  boss_kurinnaxx.cpp
  boss_moam.cpp
  boss_ossirian.cpp
  boss_rajaxx.cpp
  instance_ruins_of_ahnqiraj.cpp
  ruins_of_ahnqiraj.cpp
  silithus.cpp
  stonetalon_mountains.cpp
  tanaris.cpp
  teldrassil.cpp
  boss_bug_trio.cpp
  boss_cthun.cpp
  boss_fankriss.cpp
  boss_huhuran.cpp
  boss_ouro.cpp
  boss_sartura.cpp
  boss_skeram.cpp
  boss_twinemperors.cpp
  boss_viscidus.cpp
  instance_temple_of_ahnqiraj.cpp
  Generating Code...
  Compiling...
  mob_anubisath_sentinel.cpp
  the_barrens.cpp
  thousand_needles.cpp
  thunder_bluff.cpp
  ungoro_crater.cpp
  instance_wailing_caverns.cpp
  wailing_caverns.cpp
  winterspring.cpp
  boss_zumrah.cpp
  instance_zulfarrak.cpp
  zulfarrak.cpp
  areatrigger_scripts.cpp
  bosses_emerald_dragons.cpp
  go_scripts.cpp
  guards.cpp
  item_scripts.cpp
  mob_generic_creature.cpp
  npcs_special.cpp
  npc_professions.cpp
  spell_scripts.cpp
  Generating Code...
  Compiling...
  world_map_scripts.cpp
  ScriptLoader.cpp
  system.cpp
  AuctionHouseBot.cpp
  AuctionHouseHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\AuctionHouseHandler.cpp': No such file or directory
  AuctionHouseMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\AuctionHouseMgr.cpp': No such file or directory
  Bag.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Bag.cpp': No such file or directory
  BattleGround.cpp
  BattleGroundAB.cpp
  BattleGroundAV.cpp
  BattleGroundHandler.cpp
  BattleGroundMgr.cpp
  BattleGroundWS.cpp
  Camera.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Camera.cpp': No such file or directory
  Channel.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Channel.cpp': No such file or directory
  ChannelHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ChannelHandler.cpp': No such file or directory
  ChannelMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ChannelMgr.cpp': No such file or directory
  CharacterDatabaseCleaner.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\CharacterDatabaseCleaner.cpp': No such file or directory
  CharacterHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\CharacterHandler.cpp': No such file or directory
  Chat.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Chat.cpp': No such file or directory
  Generating Code...
  Compiling...
  ChatHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ChatHandler.cpp': No such file or directory
  CombatHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\CombatHandler.cpp': No such file or directory
  ConfusedMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ConfusedMovementGenerator.cpp': No such file or directory
  Corpse.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Corpse.cpp': No such file or directory
  Creature.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Creature.cpp': No such file or directory
  CreatureLinkingMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\CreatureLinkingMgr.cpp': No such file or directory
  DBCStores.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\DBCStores.cpp': No such file or directory
  debugcmds.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\debugcmds.cpp': No such file or directory
  DuelHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\DuelHandler.cpp': No such file or directory
  DynamicObject.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\DynamicObject.cpp': No such file or directory
  FleeingMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\FleeingMovementGenerator.cpp': No such file or directory
  FollowerReference.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\FollowerReference.cpp': No such file or directory
  GameEventMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GameEventMgr.cpp': No such file or directory
  GameObject.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GameObject.cpp': No such file or directory
  GMTicketHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GMTicketHandler.cpp': No such file or directory
  GMTicketMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GMTicketMgr.cpp': No such file or directory
  GossipDef.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GossipDef.cpp': No such file or directory
  GridMap.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GridMap.cpp': No such file or directory
  GridNotifiers.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GridNotifiers.cpp': No such file or directory
  GridStates.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GridStates.cpp': No such file or directory
  Generating Code...
  Compiling...
  Group.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Group.cpp': No such file or directory
  GroupHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GroupHandler.cpp': No such file or directory
  GroupReference.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GroupReference.cpp': No such file or directory
  Guild.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Guild.cpp': No such file or directory
  GuildHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GuildHandler.cpp': No such file or directory
  GuildMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\GuildMgr.cpp': No such file or directory
  HomeMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\HomeMovementGenerator.cpp': No such file or directory
  HostileRefManager.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\HostileRefManager.cpp': No such file or directory
  IdleMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\IdleMovementGenerator.cpp': No such file or directory
  InstanceData.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\InstanceData.cpp': No such file or directory
  Item.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Item.cpp': No such file or directory
  ItemEnchantmentMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ItemEnchantmentMgr.cpp': No such file or directory
  ItemHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ItemHandler.cpp': No such file or directory
  Level0.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Level0.cpp': No such file or directory
  Level1.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Level1.cpp': No such file or directory
  Level2.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Level2.cpp': No such file or directory
  Level3.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Level3.cpp': No such file or directory
  LootHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\LootHandler.cpp': No such file or directory
  LootMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\LootMgr.cpp': No such file or directory
  Mail.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Mail.cpp': No such file or directory
  Generating Code...
  Compiling...
  MailHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MailHandler.cpp': No such file or directory
  Map.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Map.cpp': No such file or directory
  MapManager.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MapManager.cpp': No such file or directory
  MapPersistentStateMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MapPersistentStateMgr.cpp': No such file or directory
  MassMailMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MassMailMgr.cpp': No such file or directory
  MiscHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MiscHandler.cpp': No such file or directory
  MotionMaster.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MotionMaster.cpp': No such file or directory
  MoveMap.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MoveMap.cpp': No such file or directory
  MovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MovementGenerator.cpp': No such file or directory
  MovementHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\MovementHandler.cpp': No such file or directory
  MoveSpline.cpp
  MoveSplineInit.cpp
  packet_builder.cpp
  spline.cpp
  util.cpp
  NPCHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\NPCHandler.cpp': No such file or directory
  Object.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Object.cpp': No such file or directory
  ObjectAccessor.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ObjectAccessor.cpp': No such file or directory
  ObjectGridLoader.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ObjectGridLoader.cpp': No such file or directory
  ObjectMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ObjectMgr.cpp': No such file or directory
  Generating Code...
  Compiling...
  ObjectGuid.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ObjectGuid.cpp': No such file or directory
  ObjectPosSelector.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ObjectPosSelector.cpp': No such file or directory
  Opcodes.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Opcodes.cpp': No such file or directory
  PathFinder.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\PathFinder.cpp': No such file or directory
  Pet.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Pet.cpp': No such file or directory
  PetHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\PetHandler.cpp': No such file or directory
  PetitionsHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\PetitionsHandler.cpp': No such file or directory
  Player.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Player.cpp': No such file or directory
  PlayerbotAI.cpp
..\..\src\game\playerbot\PlayerbotAI.cpp(1395): warning C4806: '!=': unsafe operation: no value of type 'bool' promoted to type 'CreatureLootStatus' can equal the given constant
..\..\src\game\playerbot\PlayerbotAI.cpp(5154): warning C4800: 'uint32': forcing value to bool 'true' or 'false' (performance warning)
  PlayerbotClassAI.cpp
  PlayerbotDruidAI.cpp
..\..\src\game\playerbot\PlayerbotDruidAI.cpp(722): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
  PlayerbotHunterAI.cpp
..\..\src\game\playerbot\PlayerbotHunterAI.cpp(321): warning C4806: '!=': unsafe operation: no value of type 'bool' promoted to type 'SpellCastResult' can equal the given constant
  PlayerbotMageAI.cpp
  PlayerbotMgr.cpp
  PlayerbotPaladinAI.cpp
  PlayerbotPriestAI.cpp
..\..\src\game\playerbot\PlayerbotPriestAI.cpp(532): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
  PlayerbotRogueAI.cpp
  PlayerbotShamanAI.cpp
  PlayerbotWarlockAI.cpp
  PlayerbotWarriorAI.cpp
  Generating Code...
c:\portalclassic\src\game\playerbot\playerbotwarlockai.cpp(466): warning C4715: 'PlayerbotWarlockAI::CheckCurse': not all control paths return a value
c:\portalclassic\src\game\playerbot\playerbotmgr.cpp(1156): warning C4715: 'ChatHandler::HandlePlayerbotCommand': not all control paths return a value
c:\portalclassic\src\game\playerbot\playerbotmgr.cpp(460): warning C4700: uninitialized local variable 'unk1' used
  Compiling...
  PlayerDump.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\PlayerDump.cpp': No such file or directory
  PointMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\PointMovementGenerator.cpp': No such file or directory
  PoolManager.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\PoolManager.cpp': No such file or directory
  QueryHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\QueryHandler.cpp': No such file or directory
  QuestDef.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\QuestDef.cpp': No such file or directory
  QuestHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\QuestHandler.cpp': No such file or directory
  RandomMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\RandomMovementGenerator.cpp': No such file or directory
  ReputationMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ReputationMgr.cpp': No such file or directory
  ScriptMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ScriptMgr.cpp': No such file or directory
  SkillHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SkillHandler.cpp': No such file or directory
  SocialMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SocialMgr.cpp': No such file or directory
  Spell.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Spell.cpp': No such file or directory
  SpellAuras.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SpellAuras.cpp': No such file or directory
  SQLStorages.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SQLStorages.cpp': No such file or directory
  UnitAuraProcHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\UnitAuraProcHandler.cpp': No such file or directory
  SpellEffects.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SpellEffects.cpp': No such file or directory
  SpellHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SpellHandler.cpp': No such file or directory
  SpellMgr.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\SpellMgr.cpp': No such file or directory
  StatSystem.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\StatSystem.cpp': No such file or directory
  TargetedMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\TargetedMovementGenerator.cpp': No such file or directory
  Generating Code...
  Compiling...
  TaxiHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\TaxiHandler.cpp': No such file or directory
  TemporarySummon.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\TemporarySummon.cpp': No such file or directory
  ThreatManager.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\ThreatManager.cpp': No such file or directory
  Totem.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Totem.cpp': No such file or directory
  TradeHandler.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\TradeHandler.cpp': No such file or directory
  Transports.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Transports.cpp': No such file or directory
  Unit.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Unit.cpp': No such file or directory
  UpdateData.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\UpdateData.cpp': No such file or directory
  WaypointManager.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\WaypointManager.cpp': No such file or directory
  WaypointMovementGenerator.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\WaypointMovementGenerator.cpp': No such file or directory
  Weather.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\Weather.cpp': No such file or directory
  World.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\World.cpp': No such file or directory
  OutdoorPvP.cpp
  OutdoorPvPEP.cpp
  OutdoorPvPMgr.cpp
  OutdoorPvPSI.cpp
  WorldSession.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\WorldSession.cpp': No such file or directory
  WorldSocket.cpp
c1xx : fatal error C1083: Cannot open source file: '..\..\src\game\WorldSocket.cpp': No such file or directory
  BIH.cpp
  DynamicTree.cpp
  Generating Code...
  Compiling...
  GameObjectModel.cpp
  MapTree.cpp
  ModelInstance.cpp
  TileAssembler.cpp
  VMapFactory.cpp
  VMapManager2.cpp
  WorldModel.cpp
  Generating Code...
------ Build started: Project: realmd, Configuration: Release x64 ------
  AuthSocket.cpp
  Main.cpp
c:\portalclassic\src\shared\revision.h(6): warning C4005: 'VERSION': macro redefinition
  c:\portalclassic\src\shared\revision.h(6): note: command-line arguments:  see previous definition of 'VERSION'
  RealmList.cpp
  WheatyExceptionReport.cpp
C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
c:\portalclassic\src\shared\revision.h(6): warning C4005: 'VERSION': macro redefinition
  c:\portalclassic\src\shared\revision.h(6): note: command-line arguments:  see previous definition of 'VERSION'
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc140-mt-1_60.lib'
------ Build started: Project: mangosd, Configuration: Release x64 ------
  stdsoap2.cpp
  soapServer.cpp
  soapC.cpp
  MaNGOSsoap.cpp
  CliRunnable.cpp
C:\portalclassic\src\game\playerbot/PlayerbotAI.h(502): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
  Main.cpp
c:\portalclassic\src\shared\revision.h(6): warning C4005: 'VERSION': macro redefinition
  c:\portalclassic\src\shared\revision.h(6): note: command-line arguments:  see previous definition of 'VERSION'
  Master.cpp
c:\portalclassic\src\shared\revision.h(6): warning C4005: 'VERSION': macro redefinition
  c:\portalclassic\src\shared\revision.h(6): note: command-line arguments:  see previous definition of 'VERSION'
  RASocket.cpp
C:\portalclassic\src\game\playerbot/PlayerbotAI.h(502): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
  WorldRunnable.cpp
C:\portalclassic\src\game\playerbot/PlayerbotAI.h(502): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
  WheatyExceptionReport.cpp
C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(1544): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
C:\Program Files (x86)\Windows Kits\8.1\Include\um\dbghelp.h(3190): warning C4091: 'typedef ': ignored on left of '' when no variable is declared
c:\portalclassic\src\shared\revision.h(6): warning C4005: 'VERSION': macro redefinition
  c:\portalclassic\src\shared\revision.h(6): note: command-line arguments:  see previous definition of 'VERSION'
  Generating Code...
LINK : fatal error LNK1181: cannot open input file 'C:\portalclassic\win\VC140\game__x64_Release\game.lib'
========== Build: 6 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========`

**Comment by cala** [comment]
I suggest to clean your solution: your VS is searching for files that were renamed/moved.
If this still don't work, try to build an unmoddified core.

**Comment by madmax765** [comment]
thanks cala. but it is cmangos it's self  On May 4 it complies ok, and may 5 dose not.. so the trouble starts on may 5th

https://github.com/cmangos/issues/issues/1369

**Comment by madmax765** [comment]
Cala can you do a mearge again with cmangs... it now fixed :D
a5492fb947ff60fad95d7f5217bf4757959819be
