### ISSUE TITLE
[Bug] Bots do no auto-accept quests

### ISSUE THREAD

**Issue by cala** [blueboy/portalclassic#6]
When player accepts a quest from a NPC, bots do not auto accept them (even for quest series). Everything else works fine:
- they accept the quest if player shares it
- they get credit for killing creatures, looting quest items...
- thus, they can complete quest (except exploring quest)
- they can auto reward quest or ask player for which reward they must choose

If player has GM right, they can give the quest to bots when quest is not sharable, but normal players are stuck.

This is not a new issue but I did not report it before.
If quest is taken from a gameobject, bots seem to auto-accept it however (must be confirmed).

**Comment by ponboynd** [comment]
Just fixed this in one of my branches. The error is in the PlayerbotMgr.cpp file.

In the HandleMasterIncomingPacket method under the CMSG_QUESTGIVER_ACCEPT_QUEST opcode change the following line:

from 
p >> guid >> quest >> unk1;

to
p >> guid >> quest;

Apparently there wasn't enough data in the packet to pull out another unint32 data type so it was erroring out. My guess is that is something that was added in future patch/expansion and was just never removed for vanilla. Hope this helps!

**Comment by cala** [comment]
Nice, thank you for this, I'll try it soon. :+1:
